#!/usr/bin/env python3
"""Build and package NMI v1.13 submission figures and tables.

This is a presentation-only publication build from already-completed frozen outputs.
"""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "outputs" / "nmi_submission_assets_v1" / "latest"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def run(script: str) -> None:
    cmd = [sys.executable, str(ROOT / "scripts" / "paper" / script)]
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=ROOT, check=True)


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True, exist_ok=True)
    run("build_nmi_submission_figures_v1.py")
    run("build_nmi_submission_tables_v1_1.py")

    files = sorted(p for p in OUT.rglob("*") if p.is_file())
    expected_figs = [OUT / "figures" / f"{stem}.{ext}" for stem in ["figure1","figure2","figure3","figure4","extended_data_figure1"] for ext in ["pdf","svg","png"]]
    expected_tables = [OUT / "tables" / f"{stem}.csv" for stem in [
        "extended_data_table_1","extended_data_table_2","extended_data_table_3","extended_data_table_4",
        "supplementary_table_1","supplementary_table_2","supplementary_table_3","supplementary_table_4","supplementary_table_5",
        "supplementary_table_6","supplementary_table_7","supplementary_table_8","supplementary_table_9","supplementary_table_10",
    ]]
    missing=[str(p.relative_to(ROOT)) for p in expected_figs+expected_tables if not p.exists()]
    if missing:
        raise RuntimeError("Submission asset build missing expected outputs: "+", ".join(missing))

    manifest={
        "schema_version":1,
        "analysis":"NeuroSem NMI v1.13 submission asset package",
        "status":"ok",
        "guardrails":[
            "Publication/presentation build only from already-completed frozen outputs.",
            "No model fitting, target selection, new neural analysis, dose selection or hypothesis search.",
            "All manuscript and supplementary quantitative tables are exported by repository Python code.",
            "All manuscript and Extended Data figures are generated by repository Python code."
        ],
        "files":{str(p.relative_to(OUT)):sha256(p) for p in sorted(expected_figs+expected_tables+[OUT/"figures/source_manifest.json",OUT/"tables/source_manifest.json"])},
    }
    manifest_path=OUT/"manifest.json"; manifest_path.write_text(json.dumps(manifest,indent=2)+"\n",encoding="utf-8")
    report=OUT/"report.txt"
    report.write_text(
        "NeuroSem NMI v1.13 submission asset build\n"
        "Status: ok\n"
        "Main figures: 4\n"
        "Extended Data figures: 1\n"
        "Generated tables: 14\n"
        "Formats: PDF/SVG/PNG for figures; CSV for tables\n"
        "Scientific status: presentation-only rebuild from frozen completed outputs\n",
        encoding="utf-8",
    )

    zip_path=OUT/"submission_assets.zip"
    with zipfile.ZipFile(zip_path,"w",compression=zipfile.ZIP_DEFLATED) as zf:
        for p in sorted(x for x in OUT.rglob("*") if x.is_file() and x != zip_path):
            zf.write(p,p.relative_to(OUT))
    print(json.dumps({"status":"ok","asset_count":len(expected_figs)+len(expected_tables),"zip":str(zip_path),"manifest":str(manifest_path)},indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
