#!/usr/bin/env python3
"""Canonical NMI v1.18 presentation build for main figures and submission tables.

The declared RunRelay artifact contract is kept stable: the four main figures are
written to outputs/nmi_main_figures_v3/latest. Figure 1 is replaced after the legacy
submission-figure pass by the already-built, hash-pinned provenance-linked v1.18
Figure 1 artifact, so no hard-coded semantic or reliability values from the legacy
builder can enter the canonical Figure 1. The text manifest includes compact
compressed SVG payloads for deterministic manuscript assembly plus every generated table.
"""
from __future__ import annotations

import base64
import gzip
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIG_BUILDER = ROOT / "scripts/paper/build_nmi_submission_figures_v1.py"
TABLE_BUILDER = ROOT / "scripts/paper/build_nmi_submission_tables_v1_1.py"
FIG1_PROV_BUILDER = ROOT / "scripts/paper/build_nmi_figure1_provenance_v1.py"
ASSET_OUT = ROOT / "outputs/nmi_submission_assets_v1/latest"
FIG1_PROV_OUT = ROOT / "outputs/nmi_v118_figure1_provenance_v1/latest"
CANONICAL_OUT = ROOT / "outputs/nmi_main_figures_v3/latest"
PINNED_FIG1_MANIFEST_SHA256 = "42ece521c9f666d9b148cba9da3ecf24e4f2786800e43b91707818ff904201b6"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def compressed_text(path: Path) -> str:
    payload = gzip.compress(path.read_bytes(), compresslevel=9, mtime=0)
    return base64.b64encode(payload).decode("ascii")


def run(path: Path) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, str(path)], cwd=ROOT, check=False, text=True, capture_output=True)


def main() -> int:
    builders = (FIG_BUILDER, TABLE_BUILDER)
    for p in (*builders, FIG1_PROV_BUILDER):
        if not p.exists():
            raise FileNotFoundError(p)
    CANONICAL_OUT.mkdir(parents=True, exist_ok=True)

    logs = []
    for builder in builders:
        completed = run(builder)
        sys.stdout.write(completed.stdout); sys.stderr.write(completed.stderr)
        logs.append({"builder": str(builder.relative_to(ROOT)), "returncode": completed.returncode,
                     "stdout": completed.stdout[-12000:], "stderr": completed.stderr[-12000:]})
        if completed.returncode != 0:
            diagnostic = {
                "schema_version": 7,
                "analysis": "NMI v1.18 submission presentation build diagnostic",
                "status": "failed",
                "logs": logs,
                "guardrails": [
                    "Presentation build only; no scientific analysis or input changes.",
                    "Failure output is written to the already-declared source_manifest.json artifact."
                ],
            }
            (CANONICAL_OUT / "source_manifest.json").write_text(json.dumps(diagnostic, indent=2) + "\n", encoding="utf-8")
            return completed.returncode

    figdir = ASSET_OUT / "figures"
    tabledir = ASSET_OUT / "tables"

    # Canonical Figure 1 must come from the previously completed provenance-linked
    # M4V8K2R6 artifact. Verify its exact source-manifest hash before copying.
    fig1_manifest = FIG1_PROV_OUT / "source_manifest.json"
    if not fig1_manifest.exists():
        raise FileNotFoundError(fig1_manifest)
    observed_fig1_manifest_sha = sha256(fig1_manifest)
    if observed_fig1_manifest_sha != PINNED_FIG1_MANIFEST_SHA256:
        raise RuntimeError(
            "Pinned Figure 1 provenance manifest mismatch: "
            f"expected {PINNED_FIG1_MANIFEST_SHA256}, observed {observed_fig1_manifest_sha}"
        )
    for ext in ("pdf", "svg", "png"):
        src = FIG1_PROV_OUT / f"figure1.{ext}"
        dst = figdir / f"figure1.{ext}"
        if not src.exists():
            raise FileNotFoundError(src)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)

    required=[]
    main_svg_paths={}
    for stem in ("figure1", "figure2", "figure3", "figure4"):
        for ext in ("pdf", "svg", "png"):
            src=figdir/f"{stem}.{ext}"; dst=CANONICAL_OUT/f"{stem}.{ext}"
            if not src.exists(): raise FileNotFoundError(src)
            shutil.copy2(src,dst); required.append(dst)
        main_svg_paths[stem]=CANONICAL_OUT/f"{stem}.svg"
    ext_svg = figdir / "extended_data_figure1.svg"
    if not ext_svg.exists(): raise FileNotFoundError(ext_svg)
    tables = sorted(tabledir.glob("*.csv"))
    if len(tables) != 14:
        raise RuntimeError(f"Expected 14 generated submission tables, found {len(tables)}")

    manifest={
        "schema_version":7,
        "analysis":"NeuroSem NMI v1.18 submission presentation build",
        "status":"ok",
        "guardrails":[
            "All quantitative figure panels and tables are generated by repository Python code from already-completed frozen derived outputs.",
            "No model fitting, target selection, neural analysis, dose selection or new scientific hypothesis search is performed.",
            "Canonical Figure 1 is copied from the exact hash-pinned M4V8K2R6 provenance artifact after the legacy submission builder completes.",
            "Figure 1 scientific values were loaded from the development summary, S0YJMCMF reliability replay and two frozen task-level C-MTEB STS summaries; no outcome-valued canonical Figure 1 panel uses legacy hard-coded constants.",
            "SVG payloads are gzip-compressed then base64-encoded only for deterministic manuscript assembly; decoded hashes equal declared SVG artifacts."
        ],
        "builders":[str(p.relative_to(ROOT)) for p in builders],
        "figure1_provenance_builder":str(FIG1_PROV_BUILDER.relative_to(ROOT)),
        "figure1_provenance_source_manifest":str(fig1_manifest.relative_to(ROOT)),
        "figure1_provenance_source_manifest_sha256":observed_fig1_manifest_sha,
        "outputs":{str(p.relative_to(ROOT)):sha256(p) for p in required},
        "main_figure_svg_gzip_b64":{stem:compressed_text(path) for stem,path in main_svg_paths.items()},
        "main_figure_svg_sha256":{stem:sha256(path) for stem,path in main_svg_paths.items()},
        "extended_data_figure1_svg_gzip_b64":compressed_text(ext_svg),
        "extended_data_figure1_svg_sha256":sha256(ext_svg),
        "submission_tables":{p.name:p.read_text(encoding="utf-8") for p in tables},
        "submission_table_sha256":{p.name:sha256(p) for p in tables},
    }
    (CANONICAL_OUT/"source_manifest.json").write_text(json.dumps(manifest,separators=(",",":"))+"\n",encoding="utf-8")
    print(json.dumps({"status":"ok","main_figures":4,"generated_tables":len(tables),"canonical_output":str(CANONICAL_OUT),"figure1_provenance_linked":True},indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
