#!/usr/bin/env python3
"""Canonical NMI v1.13 presentation build for main figures and submission tables.

The declared RunRelay artifact contract is kept stable: the four main figures are
written to outputs/nmi_main_figures_v3/latest and the source manifest embeds the
Extended Data SVG plus every repository-generated table as UTF-8 CSV text.
"""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIG_BUILDER = ROOT / "scripts/paper/build_nmi_submission_figures_v1.py"
TABLE_BUILDER = ROOT / "scripts/paper/build_nmi_submission_tables_v1_1.py"
ASSET_OUT = ROOT / "outputs/nmi_submission_assets_v1/latest"
CANONICAL_OUT = ROOT / "outputs/nmi_main_figures_v3/latest"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def run(path: Path) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, str(path)], cwd=ROOT, check=False, text=True, capture_output=True)


def main() -> int:
    for p in (FIG_BUILDER, TABLE_BUILDER):
        if not p.exists():
            raise FileNotFoundError(p)
    CANONICAL_OUT.mkdir(parents=True, exist_ok=True)

    logs = []
    for builder in (FIG_BUILDER, TABLE_BUILDER):
        completed = run(builder)
        sys.stdout.write(completed.stdout); sys.stderr.write(completed.stderr)
        logs.append({"builder": str(builder.relative_to(ROOT)), "returncode": completed.returncode,
                     "stdout": completed.stdout[-12000:], "stderr": completed.stderr[-12000:]})
        if completed.returncode != 0:
            diagnostic = {
                "schema_version": 4,
                "analysis": "NMI v1.13 submission presentation build diagnostic",
                "status": "failed",
                "logs": logs,
                "guardrails": [
                    "Presentation build only; no scientific analysis or input changes.",
                    "Failure output is written to the already-declared source_manifest.json artifact."
                ],
            }
            (CANONICAL_OUT / "source_manifest.json").write_text(json.dumps(diagnostic, indent=2) + "\n", encoding="utf-8")
            return completed.returncode

    figdir = ASSET_OUT / "figures"
    tabledir = ASSET_OUT / "tables"
    required=[]
    for stem in ("figure1", "figure2", "figure3", "figure4"):
        for ext in ("pdf", "svg", "png"):
            src=figdir/f"{stem}.{ext}"; dst=CANONICAL_OUT/f"{stem}.{ext}"
            if not src.exists(): raise FileNotFoundError(src)
            shutil.copy2(src,dst); required.append(dst)
    ext_svg = figdir / "extended_data_figure1.svg"
    if not ext_svg.exists(): raise FileNotFoundError(ext_svg)
    tables = sorted(tabledir.glob("*.csv"))
    if len(tables) != 14:
        raise RuntimeError(f"Expected 14 generated submission tables, found {len(tables)}")

    manifest={
        "schema_version":4,
        "analysis":"NeuroSem NMI v1.13 submission presentation build",
        "status":"ok",
        "guardrails":[
            "All quantitative figure panels and tables are generated by repository Python code from already-completed frozen derived outputs.",
            "No model fitting, target selection, neural analysis, dose selection or new scientific hypothesis search is performed.",
            "Figure 1a contains an explicitly labelled schematic RDM only; all outcome-valued panels use frozen outputs.",
            "The Extended Data figure is embedded here as SVG text because the stable RunRelay artifact contract declares only the four main figures plus this manifest."
        ],
        "builders":[str(FIG_BUILDER.relative_to(ROOT)),str(TABLE_BUILDER.relative_to(ROOT))],
        "outputs":{str(p.relative_to(ROOT)):sha256(p) for p in required},
        "extended_data_figure1_svg":ext_svg.read_text(encoding="utf-8"),
        "extended_data_figure1_svg_sha256":sha256(ext_svg),
        "submission_tables":{p.name:p.read_text(encoding="utf-8") for p in tables},
        "submission_table_sha256":{p.name:sha256(p) for p in tables},
        "figure_source_manifest":json.loads((figdir/"source_manifest.json").read_text(encoding="utf-8")),
        "table_source_manifest":json.loads((tabledir/"source_manifest.json").read_text(encoding="utf-8")),
    }
    (CANONICAL_OUT/"source_manifest.json").write_text(json.dumps(manifest,indent=2)+"\n",encoding="utf-8")
    print(json.dumps({"status":"ok","main_figures":4,"generated_tables":len(tables),"canonical_output":str(CANONICAL_OUT)},indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
